stages:
  - lint
  #- test
  - build

lint-pylint:
  stage: lint
  image: python:3.12-slim
  script:
    - pip install --no-cache-dir -r requirements.txt
    - pip install pylint
    - pylint app.py

#test-app:
#  stage: test
#  image: python:3.12-slim
#  script:
#    - pip install --no-cache-dir -r requirements.txt
#    - pip install pytest pytest-flask
#    - python -m pytest -v

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.20.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  rules:
    - if: $CI_COMMIT_TAG
